---
- name: CFD Librairies for main applications
  become: True
  yum:
    name:
      - pax
      - libSM
      - libX11
      - libXext
      - libXt
      - redhat-lsb-core
      - libGLU
      - libXrender.x86_64
      - libXtst.x86_64
      - motif-2.3.4-14.el7_5.x86_64
      - mesa-libGLU-9.0.0-4.el7.x86_64
      - mesa-libGLU
      - mesa-libGL
      - motif
      - fontconfig
      - fontconfig-devel
      - libXext
      - libXrender-devel.x86_64
      - libXrender.x86_64
      - mesa-libGL.x86_64
      - tmux
      - glibc.i686
      - zlib.i686
    state: present

# tasks file for fluent

- name: Create /nfs//fluent/install
  become: true
  file:
    path: "/nfs/scratch/fluent/install"
    state: directory
    owner: opc
    mode: 0770
    group: opc
    recurse: yes
    
- name: download fluent binaries
  get_url: 
    url: "{{fluent_binaries}}"  
    dest: "/nfs/scratch/fluent/install"
    mode: 0770

- name: untar fluent binaries
  unarchive: 
    src: "{{ item }}" 
    dest: "/nfs/scratch/fluent/install" 
  with_fileglob:
    - "/nfs/scratch/fluent/install/*"

- name: install fluent
  become: true 
  shell: "./INSTALL -silent -install_dir '/nfs/scratch/fluent/install' -fluent -licserverinfo {{fluent_license_port}}:{{fluent_flexnet_port}}:{{fluent_license_server_ip}}"
  args:
    chdir: "/nfs/scratch/fluent/install"
 
# Post Installation 

- name: make models directory
  ansible.builtin.file:
    path: "/nfs/scratch/fluent/models"
    state: directory
    recurse: yes
    owner: opc
    group: opc
    mode: '0777'

- name: download model 
  get_url: 
    url: "https://objectstorage.us-phoenix-1.oraclecloud.com/p/mc0PPM-M6qCC7PR5zFwLzom5XXz4YBWo6waCupaMxUQ/n/hpc/b/HPC_BENCHMARKS/o/f1_racecar_140m.tar"
    dest: "/nfs/scratch/fluent/models"
    mode: '0777' 

- name: untar model
  unarchive: 
    src: "{{ item }}" 
    dest: "/nfs/scratch/fluent/models" 
  with_fileglob:
    - "/nfs/scratch/fluent/models/*"

- name: make f1_racecar_140m directory
  ansible.builtin.file:
    path: "/nfs/scratch/fluent/models/f1_racecar_140m"
    state: directory
    recurse: yes
    owner: opc
    group: opc
    mode: '0777'

- name: move files into f1_racecar_140m folder
  copy: 
    src: "{{ item }}" 
    dest: "/nfs/scratch/fluent/models/f1_racecar_140m"
  with_fileglob:
    - "/nfs/scratch/fluent/models/bench/fluent/v6/f1_racecar_140m/cas_dat/*"

- name: gunzip f1_racecar_140m folder
  shell: "gunzip /nfs/scratch/fluent/models/f1_racecar_140m/*"
  args:
    chdir: "/nfs/scratch/fluent/models/f1_racecar_140m"

- name: delete bench folder
  ansible.builtin.file:
    path: "/nfs/scratch/fluent/models/bench"
    state: absent
    


